name: healthcheck Cron job

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # min, hour, day, month (1 - 12 or JAN-DEC), day of week (0 - 6 or SUN-SAT)
    # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#scheduled-events
    - cron: '30 10 * * *'
jobs:
  periodicCheck:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v2
        with:
          # Check the following URLs one by one sequentially
          url: "https://node-fullstackopen-part3.herokuapp.com/health"
          # Follow redirects, or just report success on 3xx status codes
          follow-redirect: false # Optional, defaults to "false"
          # Fail this action after this many failed attempts
          max-attempts: 3 # Optional, defaults to 1
          # Delay between retries
          retry-delay: 5s # Optional, only applicable to max-attempts > 1
          # Retry all errors, including 404. This option might trigger curl upgrade.
          retry-all: false # Optional, defaults to "false"